### ISSUE TITLE
how can i set border radius for gridview?

### ISSUE THREAD

**Issue by MahdiPishguy** [hugocastelani/drag_select_grid_view#11]
for `GridView` of flutter feature i can use `ClipRRect` or `Card` to make border radius for around items, but in this library it doesn't work 

for example this code work fine with border radius

```dart
child: Card(
  elevation: 0.0,
  clipBehavior: Clip.antiAliasWithSaveLayer,
  shape: const RoundedRectangleBorder(
      borderRadius: BorderRadius.only(
        topLeft: Radius.circular( 8.0 ),
        topRight: Radius.circular( 8.0 ),
      ) ),
  child: StreamBuilder<List<MediaModel>>(
      stream: _globalBloc.storageMediaBloc.imagesMedia$,
      builder: (context, snapshot) {
        ...
        return GridView.builder(
          controller: scrollController,
          cacheExtent: 100,
          gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
```

**Comment by hugocastelani** [comment]
What exactly is the problem you are facing? I ran some code with the card you mentioned and the items of my grid are rounded.

The [`SelectableItem` of the example](https://github.com/hugocbpassos/drag_select_grid_view/blob/master/example/lib/selectable_item.dart) is actually rounded. You may want to take a look at that.

**Comment by MahdiPishguy** [comment]
@hugocastelani borderRadius around GridView not Items

**Comment by MahdiPishguy** [comment]
@hugocastelani how can i use `ClipRRect` outside of `DragSelectGridView` ? for example?

``dart
return ClipRRect(
  clipBehavior: Clip.antiAliasWithSaveLayer,
  borderRadius: BorderRadius.circular(20.0),
  child: DragSelectGridView(
    gridController: controller,
    scrollController: scrollController,
    padding: const EdgeInsets.all(8),
    itemCount: _imagesFiles.length,
    itemBuilder: (context, index, selected) {
```

**Comment by hugocastelani** [comment]
Hey, @MahdiPishguy. I'm sorry for the delay.

`DragSelectGridView` should not interfere in any sort of clipping. 

I believe you may have had the impression that the clip didn't caught `DragSelectGridView` because of the padding around it. If you move the padding above the clipping, you should be able to see it:

```dart
// Move the padding above the clipping.
Padding(
  padding: const EdgeInsets.all(8),
  child: ClipRRect(
    borderRadius: BorderRadius.circular(8),
    child: DragSelectGridView(
      // Make sure to not use this padding.
      // padding: const EdgeInsets.all(8),
      gridController: controller,
      ...
```

I'm closing this for now. Feel free to reopen this up if my answer was not satisfying :)

**Comment by Faizi-Apps** [comment]
there is no borderRadius property of clipRect

**Comment by hcbpassos** [comment]
@Faizi-Apps The widget we are talking about is `ClipRRect`, not `ClipRect` (mind the "R"). The "R" stands for "Rounded". That's why it has the property `borderRadius`, unlike `ClipRect` :)
